### ISSUE TITLE
Compatibility with other linux flavours

### ISSUE THREAD

**Issue by brookst** [flightaware/piaware#2]
I've been running piaware on Arch linux with just a few minor patches. The latest commit 7b484a795581885ff1e835a5ba83ae66dab3bcce depends on dpkg existing. Arch uses pacman instead and the error from using dpkg is unhandled. Would it be possible to fix this? Or would patches be welcome? (Not that I've ever written Tcl before)

**Comment by anish** [comment]
I actually managed to get this working on Archlinux + Archlinux arm, needed a few patches but otherwise not too bad. Aur link [here](https://aur.archlinux.org/packages/piaware-git/) but it would definitely be nice for piaware to not be dependent on dpkg

**Comment by bovine** [comment]
If you have patches available, please submit them as a pull request to this repo so that we can consider merging them.

**Comment by anish** [comment]
Already done

**Comment by anish** [comment]
Here's the pull request for reference https://github.com/flightaware/piaware/pull/8

**Comment by anish** [comment]
Say @bovine don't I know you from flightlogg.in ?

**Comment by bovine** [comment]
Yes, I have submitted a few patches there too.

**Comment by dschaper** [comment]
Haven't had a chance to see how this progressed, but I do see the log error about dpkg-query not being able to determine package info. The equivalent Arch command would be `pacman -Qi piaware` but I'm not sure what info dpkg is looking for, internally the version, pID and uname all seem to be found correctly?

**Comment by anish** [comment]
@dschaper Yes, this is no longer an issue as it seems to fall back to the internal version if dpkg is not found. The Archlinux equivalent is not exactly pacman -Qi as the package resides in AUR, and I am not a TU so can't move this over to community.

**Comment by dschaper** [comment]
Hmm, seems to come up with the info on my Arch Alarm. I use your PGK with a few modifications to package the piaware-git and then pacman -U it. (Actually, yaourt, but same thing...)

**Comment by anish** [comment]
Same here. Can you let me know what modifications  you do ? I'll incorporate them if required

**Comment by dschaper** [comment]
Just some housekeeping in the package. Is the email address in the PKG good?

**Comment by Ressy66** [comment]
why does it even care.. its silly coding garbage like this that stops us for example using Slackware or 
Gentoo from contributing to this project.

**Comment by mutability** [comment]
@Ressy66: What breaks on Slackware or Gentoo currently?

**Comment by mutability** [comment]
Also, the whole dpkg version reporting path can probably go away now that I've sorted out the build process and the hardcoded version always matches the package version.

**Comment by Ressy66** [comment]
@mutability  unless its been fixed very recently,  the fact it wants to know what version of dpkg or apt or some crap and invalidates the build because we are not using a debianised OS (if this was removed? - I must have missed the post and will try again this weekend when I get a chance)

**Comment by mutability** [comment]
@Ressy66: I just checked and piaware 2.1-2 runs just fine on a debian system with dpkg and dpkg-query disabled (via chmod -x). A little digging into the history says that this was fixed a long time ago, in October 2014: cb8bfb985d2cb7d23894a3056d577de8f12139f0. So if you are still having problems, please raise a separate issue with the specific problem you see.

**Comment by anish** [comment]
The 3.0.2 release has gone heavily backwards in this regards, especially things like `piaware ALL = NOPASSWD: /usr/sbin/invoke-rc.d`

**Comment by dschaper** [comment]
Well if they are calls to `halt`, `reboot` and `invoke-rc.d` on SystemD platforms, those all are symlinks to `systemctl`. Might be able to just add a `sudoers` allow for `piaware` to call `systemctl` and oneliner it?

**Comment by anish** [comment]
@dschaper could be. Btw, 3.0.2 working for you ?

**Comment by dschaper** [comment]
Haven't tried yet, waiting for the code to bake a little bit before I move on to it. Not as adventurous as I used to be.

**Comment by mutability** [comment]
Note that most of those commands are only used it you have remote updates
enabled. Remote updates are highly unlikely to work on anything but a
standard build anyway. Before piaware 3 the command would have been run
anyway directly as root, the sudoers file doesn't change that just makes it
possible for piaware to not run as root. As always if you have changes to
make it more generic then pull requests are welcome.

**Comment by mutability** [comment]
Also note that specifically for invoke-rc.d, piaware will try systemctl, invoke-rc.d, or direct invocation of /etc/init.d scripts depending on what is actually seen on the system.

So I am going to need a specific bug report (please raise a separate issue) if there are problems there.

**Comment by dschaper** [comment]
I'll PR if need be, but on the face it looks to be pretty much the same approach we're taking on solving the `sudo` situation. We just drop a snippet in the `/etc/sudoers.d/` directory to avoid a direct edit on `sudoers` and also to make cleanup on uninstall easier. No need to sed anything. Not sure where this is going backwards?

**Comment by anish** [comment]
@dschaper Everything works fine on Arch now, if you would like to give it a try

**Comment by dschaper** [comment]
@anish Thanks, but I don't use Arch on the Pi's anymore. (Gave up the packages as well, just don't have the kind of time anymore with the Pi-hole project taking almost all of my free time.)

**Comment by mutability** [comment]
I don't think there's anything specific left to do for this issue; if there is still breakage, please raise new issues with the details
