### ISSUE TITLE
Local Map fails to Load

### ISSUE THREAD

**Issue by jpere039** [flightaware/piaware#32]
![image](https://cloud.githubusercontent.com/assets/2119526/16529353/437a9b30-3f77-11e6-8ecf-3e531b4ac771.png)
![image](https://cloud.githubusercontent.com/assets/2119526/16529377/5e34ea98-3f77-11e6-8d8d-22f6a2e73b55.png)

Hi,
Not sure if you are aware but it looks like there is a bug with the local map display. I looked up the error code and it seems like it may be related to google changing their map API?

Thanks,
Joe

**Comment by mutability** [comment]
Yeah, it is a change that Google made, they now require an API key which doesn't really work for this case where installs are widely distributed; we're in the process of looking at fixes.

**Comment by jpere039** [comment]
cool! If I see anything I'll be sure to let you know.

**Comment by mutability** [comment]
This was fixed with the 3.0.3 releases with dump1090-fa using OL3 / OSM.
