### ISSUE TITLE
piaware changed password in config file by itself

### ISSUE THREAD

**Issue by anish** [flightaware/piaware#36]
My piaware seemed to have changed it's password from the actual password to 'olivertest' by itself at some point last week in piaware.conf. The username remained unchanged. Any idea what could have happened there ?

**Comment by mutability** [comment]
No idea - that string doesn't occur anywhere I can find.

You shouldn't set a username/password anyway though.

**Comment by mutability** [comment]
I have an email from you dating back to 08/2016 where you arranged remote access for me and used that password, though, so I'm going to guess it's related to that.

**Comment by anish** [comment]
That was tls bug I think. It's weird that it would suddenly pick up that config file, I don't have any recollection of puppet username/passwords in piaware.conf either. Is that an override configuration of some sort ?

**Comment by mutability** [comment]
Uh, piaware does nothing with puppet, I don't know what you mean?

**Comment by mutability** [comment]
To summarize:
 * flightaware-user / flightaware-password in piaware.conf control piaware login to FA only. They do nothing to system login info
 * They are obsolete and shouldn't be set
 * piaware does not ever modify those settings
 * I suspect you set them at some point in the past and don't remember doing it

**Comment by anish** [comment]
err, no puppet. I mean piaware. Sorry, wires got crossed at work.

To recap : I got a feeder offline msg from flightaware. When I login to the rpi, I see the service complain about unable to login. I run piaware-config which complains about perms on /etc/piaware.conf. I look at the file, I see olivertest set there. Removing that line makes piaware work fine again.

The olivertest is probably from when you helped debug the issue, I'm not sure why it suddenly started reading that file. I hadn't touched the rpi in about 4 months at this point.

**Comment by mutability** [comment]
It's possible that your piaware has just been connected for ages; I don't see any login attempts in the last month or so, so it was connected at least that long. Everything got disconnected yesterday so that may be why it triggered then.

**Comment by mutability** [comment]
On a related note can you fix the arch packaging so that it doesn't restart piaware when piaware exits with a fatal error; this is a common problem I see with arch installs.

**Comment by anish** [comment]
@mutability will do

**Comment by mutability** [comment]
Missed your edit. The right way is how https://github.com/flightaware/piaware/blob/master/scripts/piaware.service does it:

```
Restart=on-failure
RestartPreventExitStatus=4 6
```

**Comment by anish** [comment]
@mutability I actually moved to using that service file some time ago. I don't ship a custom one for arch anymore.
