### ISSUE TITLE
Name resolution failure on startup

### ISSUE THREAD

**Issue by brookst** [flightaware/piaware#4]
I'm getting an intermittent failure on startup of piaware (again using systemd under Arch with Tclsh8.6). My log reads the following repeatedly:

    Oct 13 12:03:08 server piaware[210]: 10/13/2014 11:03:08 connecting to FlightAware eyes.flightaware.com/1200
    Oct 13 12:03:08 server piaware[210]: 10/13/2014 11:03:08 got 'couldn't open socket: Name or service not known' to adept server at eyes.flightaware.com/1200, will try again soon...

I can't see why it can't resolve the address, given that if I stop and restart the service, the socket connects correctly. It's also pretty awkward to test since it only manifests at boot and not reliably so. Any pointers on what might be going wrong, or how to debug further?

Also possibly relevant is that my network interfaces, one of which is unconnected, seem to switch places in `/dev` so it might be somehow binding to the unconnected interface.

**Comment by mutability** [comment]
I wonder if this was resolv.conf not being reread (apparently it's read once on the first query and subsequently not re-read for the lifetime of the process unless you call res_init)
