### ISSUE TITLE
PiAware update to accommodate PI3 B+

### ISSUE THREAD

**Issue by orionjb2001** [flightaware/piaware#42]
I believe the new model can not boot using the current PiAware software, users having to update there card in the model B before using that card in a new 3 B+ and there are other issues arising with Pi Aware.  Any idea on an update being released??

**Comment by mutability** [comment]
The PiAware software itself shouldn't care, it should work fine on a 3B+.

The PiAware sdcard image first needs to be updated to stretch, then we can add support. It'll happen at some point.

**Comment by orionjb2001** [comment]
Thanks Oliver

**Comment by bhaal2** [comment]
I'm getting constant clock unstable issues with the Pi 3B+ I've tried all kinds of clock speed settings, some are more stable than others, but either way it's way less stable than other times.  Is this a sensitivity issue which could be adjusted?

**Comment by mutability** [comment]
Is the other hardware, including USB cabling, identical?

**Comment by bhaal2** [comment]
Yep, nothing changed, all I did was upgrade from Jessie to Stretch..

**Comment by bhaal2** [comment]
It seems like it took a while for the clock to settle down, like 12hrs or more, but now it seems to be ok. Seems like the clock has remained stable since this happened..

**Comment by mutability** [comment]
The 3.6.2 sdcard images are now Stretch-based.
