### ISSUE TITLE
Potential glitch with local map qwhen laptop is shut

### ISSUE THREAD

**Issue by cdrum** [flightaware/piaware#5]
Not sure if you know this, and it's probably a minor thing, but when looking at the local map (:8080) on my laptop, letting it pick up a bunch of planes, then I shut my laptop for a while, later when I open it again, the map doesn't seem to remove the old planes.

**Comment by mutability** [comment]
This was fixed in dump1090-mutability a long time ago, and now that dump1090-fa is based on that, we have the bugfix in the standard piaware images too.
