### ISSUE TITLE
Possible Security Breach.

### ISSUE THREAD

**Issue by mrbreenhd** [flightaware/piaware#56]
Hello, ive been running piaware for just over a year and have only installed what I needed to run my pi. Recently ive installed mysql with phpmyadmin for localhost use only. Less than a day of having it installed I had noticed my tables were gone and replaced with 1 table for ransomware.(what ever it wasn't important) but of course im a bit on edge on what caused it. 

Now of course I am not saying that it was caused by piaware but seeing as its the main os for my pi I thought id make a note of this and seek some help/advice on what to do.

**Comment by mutability** [comment]
Given the timing, the more likely explanation here is an insecure install of mysql or phpmyadmin. The piaware sdcard image exposes almost no services by default.
