### ISSUE TITLE
piaware blocks waiting for netstat output

### ISSUE THREAD

**Issue by mutability** [flightaware/piaware#7]
netstat without -n can take a long time to complete (minutes!) as it needs to do reverse-DNS on potentially a long list of addresses, many of which might time out.

piaware blocks while it waits for this output, which isn't great.

Best option would be to pass -n, but you'd have to do something about explicitly looking for "eyes.flightaware.com" then.

**Comment by lehenbauer** [comment]
Good point.  It could be written to not block or to use IP addresses.

**Comment by mutability** [comment]
https://github.com/mutability/piaware/commit/472af67d73130359456157fbb9057bbbce2c79c9 may be a useful starting point for you

**Comment by mutability** [comment]
#11 fixed this
