### ISSUE TITLE
Enhancement request: direct entry of latitude and longitude values when setting location

### ISSUE THREAD

**Issue by jaymot123** [flightaware/piaware#76]
The only choice when entering your location is "I would like to pick my receiver's location on a map." Please add a choice "I know my exact location and would like to enter it directly" (or however you want to word it) for those of us who already know our precise latitude and longitude.

**Comment by eric1tran** [comment]
Are you talking about your My ADS-B stats page on www.flightaware.com? If so, both of your requests are already possible.

**Comment by jaymot123** [comment]
@eric1tran yes. The only selection I see when I click on the gear icon then click manually enter location is to use the map. I find nothing that lets me manually enter my latitude and longitude.

**Comment by mutability** [comment]
You can already do this:

![Screenshot from 2021-09-13 13-27-56](https://user-images.githubusercontent.com/3055062/133028795-d3c3522b-ecad-4992-b7b2-d319cce4dd2d.png)

![Screenshot from 2021-09-13 13-28-21](https://user-images.githubusercontent.com/3055062/133028804-eb10e81e-2e7b-41a3-9fd3-6e2ede1603ed.png)

**Comment by jaymot123** [comment]
Aha! I guess I didn't scroll far enough down in the window to see that at the bottom.  (Sorry.)
