### ISSUE TITLE
basic auth for lighthttpd

### ISSUE THREAD

**Issue by cemeyer2** [flightaware/piaware#78]
Hello

Are there best practices or documentation to enable basic auth on a piaware install for the web interface?

thanks

**Comment by mutability** [comment]
Not that I'm aware of, but something like https://redmine.lighttpd.net/projects/1/wiki/HowToBasicAuth might be a good starting point assuming you're sticking with lighttpd. I'd suggest putting the config in your own parallel `/etc/lighttpd/conf-available/` if you can.

**Comment by cemeyer2** [comment]
okay thanks, can do that. I was not sure if there were implications of changing the config that might cause it to get overridden with package upgrades, etc
