### ISSUE TITLE
Upgrade from 5.0 to 6.1 from stats page fails with apt-get update error

### ISSUE THREAD

**Issue by profporridge** [flightaware/piaware#79]
I ran into an issue when trying to upgrade via the adsb stats page. It seems to be related to the script [run-apt-get](https://github.com/flightaware/piaware/blob/master/programs/piaware/helpers/run-apt-get). The command ```sudo apt-get update``` was failing when run in a terminal with the error ``` Repository 'http://archive.raspberrypi.org/debian buster InRelease' changed its 'Suite' value from 'testing' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.```

Solution was to run ```sudo apt-get update --allow-releaseinfo-change``` in a terminal. After this I was able to update successfully from the adsb stats page. 

This was on a custom install of piaware on Raspian 10

**Comment by mutability** [comment]
see https://github.com/flightaware/piaware_builder/issues/18#issuecomment-973697475 (tl;dr: out of our control and doesn't affect newer installs)
