### ISSUE TITLE
Error loop on boot prevent access to piaware

### ISSUE THREAD

**Issue by sbsrouteur** [flightaware/piaware#89]
Hi, 

After a power outage, yesterday, my piaware did not restart.
Connected a video cable to console to find that an error in a /var/lib/dpkg/status crashes a script and the boot sequence does not seem to go far enough for ssh access to console login.

It seems to just loop on this. the device nic lights up, but does not seem to go far enough to request a dhcp address from the lan.

See attached screenshot for more detailed info on the error
![image](https://user-images.githubusercontent.com/11095871/189483236-123714e1-1810-48c8-95ef-b6565dabc0c0.png)

Is there a way to get out of this loop?

Thank you for your help.

**Comment by mutability** [comment]
This is filesystem / sdcard damage. I'd suggest recovering from a backup or
reimaging, perhaps with a new sdcard.

**Comment by sbsrouteur** [comment]
sd was damaged.  Not a bug on piaware side.
